spring:
  application:
    name: psy
  profiles:
    active: h2
  ai:
    ollama:
      base-url: http://localhost:11431
    chat:
      model: gemma3:4b-it-q4_K_M

server:
  port: 8081

service:
  chat:
    mockEnabled: true
